// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NhaSach.Web.Data;

#nullable disable

namespace NhaSach.Web.Migrations
{
    [DbContext(typeof(NhaSachDbContext))]
    [Migration("20250823114033_Db_Cleanup_And_Fixes")]
    partial class Db_Cleanup_And_Fixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NhaSach.Web.Models.Baiviet", b =>
                {
                    b.Property<int>("Baiviet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Baiviet_Id"));

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung_Baiviet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_Baiviet")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TacGia_Baiviet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tieude_Baiviet")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Tomtat_Baiviet")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Baiviet_Id");

                    b.HasIndex("Slug_Baiviet");

                    b.ToTable("Baiviet");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Baiviet_Tag", b =>
                {
                    b.Property<int>("Baiviet_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_Id")
                        .HasColumnType("int");

                    b.HasKey("Baiviet_Id", "Tag_Id");

                    b.HasIndex("Tag_Id");

                    b.ToTable("Baiviet_Tag");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Danhmuc", b =>
                {
                    b.Property<int>("Danhmuc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Danhmuc_Id"));

                    b.Property<string>("MoTa_Danhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_Danhmuc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Ten_Danhmuc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Danhmuc_Id");

                    b.HasIndex("Slug_Danhmuc");

                    b.ToTable("Danhmuc");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Donhang", b =>
                {
                    b.Property<int>("Donhang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Donhang_Id"));

                    b.Property<string>("Dia_Chi")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ho_Ten")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ma_Don")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Ngay_Dat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tong_Tien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai_Don")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("User_Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Donhang_Id");

                    b.ToTable("Donhang");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Donhang_Chitiet", b =>
                {
                    b.Property<int>("Donhang_Chitiet_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Donhang_Chitiet_Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Donhang_Id")
                        .HasColumnType("int");

                    b.Property<int>("Sanpham_Id")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Donhang_Chitiet_Id");

                    b.HasIndex("Donhang_Id");

                    b.HasIndex("Sanpham_Id");

                    b.ToTable("Donhang_Chitiet");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Giohang_Item", b =>
                {
                    b.Property<int>("Giohang_Item_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Giohang_Item_Id"));

                    b.Property<decimal>("DonGia_LucThem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sanpham_Id")
                        .HasColumnType("int");

                    b.Property<string>("Session_Id")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("User_Id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Giohang_Item_Id");

                    b.HasIndex("Sanpham_Id");

                    b.HasIndex("Session_Id", "Sanpham_Id")
                        .IsUnique();

                    b.ToTable("Giohang_Item");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Sanpham", b =>
                {
                    b.Property<int>("Sanpham_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sanpham_Id"));

                    b.Property<bool>("Con_Hang")
                        .HasColumnType("bit");

                    b.Property<int>("Danhmuc_Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaKhuyenMai")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Gia_KhuyenMai");

                    b.Property<decimal>("Gia_Ban")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh_Chinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTaNgan_Sanpham")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("MoTa_Sanpham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SKU_Sanpham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoLuong_Ton")
                        .HasColumnType("int");

                    b.Property<string>("TacGia")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ten_Sanpham")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Sanpham_Id");

                    b.HasIndex("Danhmuc_Id");

                    b.HasIndex("SKU_Sanpham");

                    b.ToTable("Sanpham");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Sukien", b =>
                {
                    b.Property<int>("Sukien_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sukien_Id"));

                    b.Property<string>("Banner_Sukien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("BatDau_Sukien")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diadiem_Sukien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("KetThuc_Sukien")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mota_Sukien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_Sukien")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tieude_Sukien")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Sukien_Id");

                    b.HasIndex("Slug_Sukien");

                    b.ToTable("Sukien");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Tag", b =>
                {
                    b.Property<int>("Tag_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tag_Id"));

                    b.Property<string>("Ten_Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Tag_Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("NhaSach.Web.Models.TrangNoiDung", b =>
                {
                    b.Property<int>("Trang_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trang_Id"));

                    b.Property<bool>("HienThi_Menu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Ngay_Tao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Noidung_Trang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug_Trang")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tieude_Trang")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Trang_Id");

                    b.HasIndex("Slug_Trang");

                    b.ToTable("Trang");
                });

            modelBuilder.Entity("NhaSach.Web.Models.UngDungUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dia_Chi")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ho_Ten")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("NhaSach.Web.Models.UngDungUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("NhaSach.Web.Models.UngDungUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("NhaSach.Web.Models.UngDungUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NhaSach.Web.Models.Baiviet_Tag", b =>
                {
                    b.HasOne("NhaSach.Web.Models.Baiviet", "Baiviet")
                        .WithMany("Baiviet_Tags")
                        .HasForeignKey("Baiviet_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaSach.Web.Models.Tag", "Tag")
                        .WithMany("Baiviet_Tags")
                        .HasForeignKey("Tag_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Baiviet");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Donhang_Chitiet", b =>
                {
                    b.HasOne("NhaSach.Web.Models.Donhang", "Donhang")
                        .WithMany("Chitiets")
                        .HasForeignKey("Donhang_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NhaSach.Web.Models.Sanpham", "Sanpham")
                        .WithMany("Donhang_Chitiets")
                        .HasForeignKey("Sanpham_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donhang");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Giohang_Item", b =>
                {
                    b.HasOne("NhaSach.Web.Models.Sanpham", "Sanpham")
                        .WithMany("Giohang_Items")
                        .HasForeignKey("Sanpham_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Sanpham", b =>
                {
                    b.HasOne("NhaSach.Web.Models.Danhmuc", "Danhmuc")
                        .WithMany("Sanphams")
                        .HasForeignKey("Danhmuc_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Danhmuc");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Baiviet", b =>
                {
                    b.Navigation("Baiviet_Tags");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Danhmuc", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Donhang", b =>
                {
                    b.Navigation("Chitiets");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Sanpham", b =>
                {
                    b.Navigation("Donhang_Chitiets");

                    b.Navigation("Giohang_Items");
                });

            modelBuilder.Entity("NhaSach.Web.Models.Tag", b =>
                {
                    b.Navigation("Baiviet_Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
